/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.*;
import gestionBBDD.ConectaBBDD;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia Baixauli de la Villa
 */
public class JFcond_consultaTodos extends javax.swing.JFrame {

    /**
     * Creates new form jFnewVeh
     */
    private ConectaBBDD con = new ConectaBBDD();
    private Conductor conductor;
    
    public JFcond_consultaTodos() {
        initComponents();
        setLocationRelativeTo(null);
        //ponemos el número de clientes totales

        int numCondTotal;
        try {
            con.conecta();
            con.crearSentencia();
            con.ejecutaSQL("SELECT * FROM Clientes");
            numCondTotal = con.tamanyo();
            jLtotalCond.setText(Integer.toString(numCondTotal));
            
            con.irAlPrimero();
            conductor = con.dameCondActual();
            mostrarConduc(conductor);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Conexión!!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
        }
        jTFany.setEnabled(false);
        jTFnom.setEnabled(false);
        jTFedad.setEnabled(false);
        jTFape.setEnabled(false);
        
        //mostrar el primero de la lista al cargar

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPdatosCond = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTFnom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFedad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFany = new javax.swing.JTextField();
        jLerrorpma = new javax.swing.JLabel();
        jTFape = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPintroMat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFTdni = new javax.swing.JFormattedTextField();
        jBfirst = new javax.swing.JButton();
        jBanterior = new javax.swing.JButton();
        jBnext = new javax.swing.JButton();
        jBlast = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLtotalCond = new javax.swing.JLabel();
        jPbotonera = new javax.swing.JPanel();
        jBcancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLcondAct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar conductores");
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 134, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 300));

        jPdatosCond.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Nombre:");

        jTFnom.setBackground(new java.awt.Color(153, 204, 255));
        jTFnom.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFnom.setForeground(new java.awt.Color(0, 0, 153));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Edad:");

        jTFedad.setBackground(new java.awt.Color(153, 204, 255));
        jTFedad.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFedad.setForeground(new java.awt.Color(0, 0, 153));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Años Carné:");

        jTFany.setBackground(new java.awt.Color(153, 204, 255));
        jTFany.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFany.setForeground(new java.awt.Color(0, 0, 153));

        jLerrorpma.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLerrorpma.setForeground(new java.awt.Color(255, 0, 51));
        jLerrorpma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jTFape.setBackground(new java.awt.Color(153, 204, 255));
        jTFape.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFape.setForeground(new java.awt.Color(0, 0, 153));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Apellidos:");

        javax.swing.GroupLayout jPdatosCondLayout = new javax.swing.GroupLayout(jPdatosCond);
        jPdatosCond.setLayout(jPdatosCondLayout);
        jPdatosCondLayout.setHorizontalGroup(
            jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosCondLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdatosCondLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFedad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFany, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosCondLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFape, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPdatosCondLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPdatosCondLayout.createSequentialGroup()
                            .addGap(444, 444, 444)
                            .addComponent(jLerrorpma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPdatosCondLayout.setVerticalGroup(
            jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosCondLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLerrorpma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPintroMat.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("D.N.I. :");

        jFTdni.setBackground(new java.awt.Color(255, 255, 255));
        jFTdni.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jFTdni.setForeground(new java.awt.Color(0, 0, 153));
        try {
            jFTdni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTdni.setAlignmentX(10.0F);
        jFTdni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFTdni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFTdni.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jFTdni.setPreferredSize(new java.awt.Dimension(38, 22));

        jBfirst.setBackground(new java.awt.Color(51, 134, 209));
        jBfirst.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBfirst.setForeground(new java.awt.Color(255, 255, 255));
        jBfirst.setText("l◄");
        jBfirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfirstActionPerformed(evt);
            }
        });

        jBanterior.setBackground(new java.awt.Color(51, 134, 209));
        jBanterior.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBanterior.setForeground(new java.awt.Color(255, 255, 255));
        jBanterior.setText("◄");
        jBanterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanteriorActionPerformed(evt);
            }
        });

        jBnext.setBackground(new java.awt.Color(51, 134, 209));
        jBnext.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBnext.setForeground(new java.awt.Color(255, 255, 255));
        jBnext.setText("►");
        jBnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextActionPerformed(evt);
            }
        });

        jBlast.setBackground(new java.awt.Color(51, 134, 209));
        jBlast.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBlast.setForeground(new java.awt.Color(255, 255, 255));
        jBlast.setText("►l");
        jBlast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPintroMatLayout = new javax.swing.GroupLayout(jPintroMat);
        jPintroMat.setLayout(jPintroMatLayout);
        jPintroMatLayout.setHorizontalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPintroMatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jBfirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBanterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBnext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBlast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPintroMatLayout.setVerticalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPintroMatLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBlast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar Conductores");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Conductores:");

        jLtotalCond.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLtotalCond.setForeground(new java.awt.Color(255, 255, 255));
        jLtotalCond.setText("-");

        jPbotonera.setBackground(new java.awt.Color(51, 134, 209));

        jBcancel.setBackground(new java.awt.Color(255, 0, 0));
        jBcancel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBcancel.setForeground(new java.awt.Color(255, 255, 255));
        jBcancel.setText("X");
        jBcancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbotoneraLayout = new javax.swing.GroupLayout(jPbotonera);
        jPbotonera.setLayout(jPbotoneraLayout);
        jPbotoneraLayout.setHorizontalGroup(
            jPbotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotoneraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPbotoneraLayout.setVerticalGroup(
            jPbotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotoneraLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jBcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nº de conductor:");

        jLcondAct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLcondAct.setForeground(new java.awt.Color(255, 255, 255));
        jLcondAct.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPintroMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLtotalCond, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLcondAct, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPdatosCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPbotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLtotalCond))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLcondAct))))
                .addGap(13, 13, 13)
                .addComponent(jPintroMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPdatosCond, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPbotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelActionPerformed
        dispose();
        try {
            con.cerrarConexion();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBcancelActionPerformed

    private void jBfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfirstActionPerformed
        // primer vehiculo de la lista
        try {
            if (!con.isPrincipio()) {//si no es el 1º
                con.irAlPrimero();
                conductor = con.dameCondActual();
                mostrarConduc(conductor);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBfirstActionPerformed

    private void jBanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanteriorActionPerformed
        try {
            if (!con.isPrincipio()) {//si no es el primer elemento
                con.irAlAnterior();
                conductor = con.dameCondActual();
                mostrarConduc(conductor);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBanteriorActionPerformed

    private void jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextActionPerformed
        try {
            if (!con.isFinal()) {//si no es el último
                con.irAlSiguiente();
                conductor = con.dameCondActual();
                mostrarConduc(conductor);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBnextActionPerformed

    private void jBlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlastActionPerformed
        try {
            if (!con.isFinal()) {//si no es el último
                con.irAlFinal();
                conductor = con.dameCondActual();
                mostrarConduc(conductor);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de navegación", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBlastActionPerformed

    public void mostrarConduc(Conductor cond){
        jFTdni.setText(cond.getDni());
        jTFnom.setText(cond.getNombre());
        jTFape.setText(cond.getApellidos());
        jTFedad.setText(Integer.toString(cond.getEdad()));
        jTFany.setText(Integer.toString(cond.getAnyosCarnet()));
        //numero de conductor en la lista
        try {
            jLcondAct.setText(Integer.toString(con.damePosAct()));
            actualizaBotones();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al consultar nº conductor!!", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al consultar nº conductor!!", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    private void actualizaBotones() throws SQLException {
        //se deshabilitan todos
        jBanterior.setEnabled(false);
        jBnext.setEnabled(false);
        jBfirst.setEnabled(false);
        jBlast.setEnabled(false);

        //se habilitan según la posicion
        //si hay más de un vehículo
        if (con.tamanyo() > 1) {
            if (!con.isFinal()) {//si no es el ultimo
                jBnext.setEnabled(true);
                jBlast.setEnabled(true);
            }
            if (!con.isPrincipio()) {
                jBfirst.setEnabled(true);
                jBanterior.setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanterior;
    private javax.swing.JButton jBcancel;
    private javax.swing.JButton jBfirst;
    private javax.swing.JButton jBlast;
    private javax.swing.JButton jBnext;
    private javax.swing.JFormattedTextField jFTdni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLcondAct;
    private javax.swing.JLabel jLerrorpma;
    private javax.swing.JLabel jLtotalCond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotonera;
    private javax.swing.JPanel jPdatosCond;
    private javax.swing.JPanel jPintroMat;
    private javax.swing.JTextField jTFany;
    private javax.swing.JTextField jTFape;
    private javax.swing.JTextField jTFedad;
    private javax.swing.JTextField jTFnom;
    // End of variables declaration//GEN-END:variables
}
