/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.*;
import gestionBBDD.ConectaBBDD;
import gestionBBDD.LibreriaUsoBBDD;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia Baixauli de la Villa
 */
public class JFcond_baja extends javax.swing.JFrame {

    /**
     * Creates new form jFnewVeh
     */
    ConectaBBDD con = new ConectaBBDD();

    public JFcond_baja() {
        initComponents();
        setLocationRelativeTo(null);
        
        //ponemos el número de clientes totales
        int numCond;
        try{
            con.conecta();
            con.crearSentencia();
            con.ejecutaSQL("SELECT * FROM Clientes");
            numCond = con.tamanyo();
            con.cerrarConexion();
            jLtotalCond.setText(Integer.toString(numCond));
        
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error Conexión!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!!", JOptionPane.ERROR_MESSAGE);
        }
        jTFany.setEnabled(false);
        jTFnom.setEnabled(false);
        jTFedad.setEnabled(false);
        jTFape.setEnabled(false);
        
        jBaelimina_cond.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPdatosCond = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTFnom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFedad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFany = new javax.swing.JTextField();
        jLerrorpma = new javax.swing.JLabel();
        jTFape = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPintroMat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFTdni = new javax.swing.JFormattedTextField();
        jBcheckDni_ = new javax.swing.JButton();
        jLerrorDni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLtotalCond = new javax.swing.JLabel();
        jPbotonera = new javax.swing.JPanel();
        jBcancel = new javax.swing.JButton();
        jBaelimina_cond = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja conductor");
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 134, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 300));

        jPdatosCond.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Nombre:");

        jTFnom.setBackground(new java.awt.Color(153, 204, 255));
        jTFnom.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFnom.setForeground(new java.awt.Color(0, 0, 153));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Edad:");

        jTFedad.setBackground(new java.awt.Color(153, 204, 255));
        jTFedad.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFedad.setForeground(new java.awt.Color(0, 0, 153));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Años Carné:");

        jTFany.setBackground(new java.awt.Color(153, 204, 255));
        jTFany.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFany.setForeground(new java.awt.Color(0, 0, 153));

        jLerrorpma.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLerrorpma.setForeground(new java.awt.Color(255, 0, 51));
        jLerrorpma.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jTFape.setBackground(new java.awt.Color(153, 204, 255));
        jTFape.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFape.setForeground(new java.awt.Color(0, 0, 153));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Apellidos:");

        javax.swing.GroupLayout jPdatosCondLayout = new javax.swing.GroupLayout(jPdatosCond);
        jPdatosCond.setLayout(jPdatosCondLayout);
        jPdatosCondLayout.setHorizontalGroup(
            jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosCondLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdatosCondLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFedad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFany, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosCondLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFape, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPdatosCondLayout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPdatosCondLayout.createSequentialGroup()
                            .addGap(444, 444, 444)
                            .addComponent(jLerrorpma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPdatosCondLayout.setVerticalGroup(
            jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosCondLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPdatosCondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLerrorpma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPintroMat.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Introduzca el D.N.I. :");

        jFTdni.setBackground(new java.awt.Color(255, 255, 255));
        jFTdni.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jFTdni.setForeground(new java.awt.Color(0, 0, 153));
        try {
            jFTdni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTdni.setAlignmentX(10.0F);
        jFTdni.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFTdni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFTdni.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jFTdni.setPreferredSize(new java.awt.Dimension(38, 22));

        jBcheckDni_.setBackground(new java.awt.Color(164, 164, 140));
        jBcheckDni_.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBcheckDni_.setForeground(new java.awt.Color(51, 51, 0));
        jBcheckDni_.setText("Comprobar DNI");
        jBcheckDni_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcheckDni_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcheckDni_ActionPerformed(evt);
            }
        });

        jLerrorDni.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLerrorDni.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPintroMatLayout = new javax.swing.GroupLayout(jPintroMat);
        jPintroMat.setLayout(jPintroMatLayout);
        jPintroMatLayout.setHorizontalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPintroMatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPintroMatLayout.createSequentialGroup()
                        .addComponent(jLerrorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPintroMatLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBcheckDni_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))))
        );
        jPintroMatLayout.setVerticalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPintroMatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTdni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcheckDni_, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLerrorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Eliminar Conductor");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nº conductores actuales:");

        jLtotalCond.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLtotalCond.setForeground(new java.awt.Color(255, 255, 255));
        jLtotalCond.setText("-");

        jPbotonera.setBackground(new java.awt.Color(51, 134, 209));

        jBcancel.setBackground(new java.awt.Color(255, 0, 0));
        jBcancel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBcancel.setForeground(new java.awt.Color(255, 255, 255));
        jBcancel.setText("X");
        jBcancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelActionPerformed(evt);
            }
        });

        jBaelimina_cond.setBackground(new java.awt.Color(164, 164, 140));
        jBaelimina_cond.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBaelimina_cond.setForeground(new java.awt.Color(51, 51, 0));
        jBaelimina_cond.setText("Eliminar conductor");
        jBaelimina_cond.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBaelimina_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaelimina_condActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbotoneraLayout = new javax.swing.GroupLayout(jPbotonera);
        jPbotonera.setLayout(jPbotoneraLayout);
        jPbotoneraLayout.setHorizontalGroup(
            jPbotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotoneraLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBaelimina_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPbotoneraLayout.setVerticalGroup(
            jPbotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotoneraLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPbotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBaelimina_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPintroMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLtotalCond, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPdatosCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPbotonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLtotalCond))))
                .addGap(18, 18, 18)
                .addComponent(jPintroMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPdatosCond, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPbotonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcheckDni_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcheckDni_ActionPerformed
        boolean dniOk = true,alquilado=false,existe;
        String dni = jFTdni.getText().toUpperCase();
        Conductor cond= null;
        //Si el campo no está vacío
        if (jFTdni.getValue() == null) {
            jLerrorDni.setText("Introduzca el DNI");
            jFTdni.setText("");
            jFTdni.requestFocus();
            dniOk = false;
        } else {
            try {
                dniOk = MiLibreria.controlarDNI(dni);
                jLerrorDni.setText("");
                if (dniOk) {
                    //si pasa el control, vemos si ya existe
                    try {
                        existe = LibreriaUsoBBDD.existeDni(dni);
                        if (!existe) {
                            jLerrorDni.setText("Este conductor NO está registrado");
                            jFTdni.setText("");
                            dniOk = false;
                        } else {//vemos si tiene alquiler activo
                            alquilado = LibreriaUsoBBDD.existeAlquilerDni(dni);
                            if (alquilado) {
                                JOptionPane.showMessageDialog(this, "No se puede eliminar el conductor.\n El cliente tiene un vehículo alquilado", "Alquiler activo", JOptionPane.ERROR_MESSAGE);
                                jFTdni.setText("");
                                jBaelimina_cond.setEnabled(false);
                            } else if (!alquilado) {
                                jBaelimina_cond.setEnabled(true);
                            }

                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error BBDD. Al buscar DNI!!", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
                   }
                }
            } catch (ExcepcionPropia e) {
                jLerrorDni.setText(e.getMessage());
                dniOk = false;
                jFTdni.setText("");
                jFTdni.requestFocus();
            } catch (Exception e) {
                dniOk = false;
                jLerrorDni.setText("Fallo al validar el DNI");
            }
            //comprobar si tiene alquilado algún vehículo
            
            
            if (dniOk && !alquilado) {
                //mostramos los datos
                 try {
                   con.conecta();
                   con.crearSentencia();
                   cond = con.buscaConductor(dni);
                   con.cerrarConexion();

               } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(this, ex.getMessage(), "Error al buscar conductor!!", JOptionPane.ERROR_MESSAGE);
               } catch (Exception ex) {
                   JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
               }
                //mostramos los datos del cliente
                jTFnom.setText(cond.getNombre());
                jTFape.setText(cond.getApellidos());
                jTFedad.setText(Integer.toString(cond.getEdad()));
                jTFany.setText(Integer.toString(cond.getAnyosCarnet()));
            }//fin mostrar datos
        }

    }//GEN-LAST:event_jBcheckDni_ActionPerformed

    private void jBcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelActionPerformed
        dispose();
    }//GEN-LAST:event_jBcancelActionPerformed

    private void jBaelimina_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaelimina_condActionPerformed
        String dni;
        boolean borrado = false;
        int tamanyo=-1;
        dni = jFTdni.getText().toUpperCase();

        try {
            con.conecta();
            con.crearSentencia();
            borrado = con.borraConductor(dni);
            //ver si quedan conductores
            con.cargaTabla("Clientes");
            tamanyo = con.tamanyo();
            con.cerrarConexion();
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error BBDD. Elimina conductor!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se ha eliminado el conductor", "ERROR SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
//            }
//        }
        if (borrado) {
            JOptionPane.showMessageDialog(this, "Conductor eliminado con éxito", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
            if(tamanyo==0){
                JOptionPane.showMessageDialog(this, "No hay conductores", "Lista vacía", JOptionPane.INFORMATION_MESSAGE);
            }
            dispose();
        }
    }//GEN-LAST:event_jBaelimina_condActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaelimina_cond;
    private javax.swing.JButton jBcancel;
    private javax.swing.JButton jBcheckDni_;
    private javax.swing.JFormattedTextField jFTdni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLerrorDni;
    private javax.swing.JLabel jLerrorpma;
    private javax.swing.JLabel jLtotalCond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotonera;
    private javax.swing.JPanel jPdatosCond;
    private javax.swing.JPanel jPintroMat;
    private javax.swing.JTextField jTFany;
    private javax.swing.JTextField jTFape;
    private javax.swing.JTextField jTFedad;
    private javax.swing.JTextField jTFnom;
    // End of variables declaration//GEN-END:variables
}
