/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import DAO.*;
import gestionBBDD.ConectaBBDD;
import java.sql.SQLException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia Baixauli de la Villa
 */
public class JFveh_consTodos extends javax.swing.JFrame {

    /**
     * Creates new form jFnewVeh
     */
    int numVehic = 0;
    Vehiculo vehic;
    ConectaBBDD con = new ConectaBBDD();


    public JFveh_consTodos() {
        int numTotalVehic;
        initComponents();
        setLocationRelativeTo(null);
        
       
        //ponemos el número de vehíc totales
        try{
            con.conecta();
            con.crearSentencia();
            con.ejecutaSQL("SELECT * FROM Vehiculos");
            
            //num vehic totales
            numTotalVehic = con.tamanyo();
            jLtotalVeh.setText(Integer.toString(numTotalVehic));
            
            //cargar combo color
            String[] misColor = con.arrayColores();
            for (int i = 0; i < misColor.length; i++) {
                jCcolor.addItem(misColor[i]);
            }
            
            //carga motor
            String[] miMotor = con.arrayMotores();
            for (int i = 0; i < miMotor.length; i++) {
                jCmotor.addItem(miMotor[i]);
            }
            //cargar todos los vehiculos en otro resultSet
            
            con.ejecutaSQL("SELECT *,Colores.descripcion AS 'micolor', Motores.descripcion AS 'mimotor',Tipos.descripcion AS 'tipodesc'"
                    + " FROM Vehiculos JOIN Colores,Motores,Tipos"
                    + " WHERE Vehiculos.idcolor = Colores.idcolor"
                    + " AND Vehiculos.idmotor = Motores.idmotor"
                    + " AND Vehiculos.tipo = Tipos.idtipo");
            //con el rs de la conexión vamos moviéndonos por la base de datos
            con.irAlPrimero();
            vehic = con.dameVehiAct();
            mostrarVehiculo(vehic);
            numVehic = con.damePosAct();//será 1
            
            //como muestra todos, no cerramos aqui la conexion
            //con.cerrarConexion();
        
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!!", JOptionPane.ERROR_MESSAGE);
        }
        //tods los campos menos matrícula están desactivados
        //tipo vehi
        Enumeration botonTipo = bGtipoVeh.getElements();
        while(botonTipo.hasMoreElements()){
            AbstractButton but= (AbstractButton) botonTipo.nextElement();
            but.setEnabled(false);
        }
        
        jTFmarca.setEnabled(false);
        jTFcilin.setEnabled(false);
        jTFruedas.setEnabled(false);
        jTFplazas.setEnabled(false);
        jTFpma.setEnabled(false);
        jCcolor.setEnabled(false);
        jCmotor.setEnabled(false);
        jFTmat.setEnabled(false);
        jTFmetros.setEnabled(false);
        
    }//fin constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGtipoVeh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPdatosVeh = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRcoche = new javax.swing.JRadioButton();
        jRmicro = new javax.swing.JRadioButton();
        jRcam = new javax.swing.JRadioButton();
        jRfurgo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSanVeh = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jCcolor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jCmotor = new javax.swing.JComboBox<>();
        jTFmarca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFcilin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFplazas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFpma = new javax.swing.JTextField();
        jTFmetros = new javax.swing.JTextField();
        jLmetros = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFruedas = new javax.swing.JTextField();
        jPintroMat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBanterior = new javax.swing.JButton();
        jBnext = new javax.swing.JButton();
        jFTmat = new javax.swing.JFormattedTextField();
        jBfirst = new javax.swing.JButton();
        jBlast = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLtotalVeh = new javax.swing.JLabel();
        jBexit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLvehAct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar vehículos");
        setBackground(new java.awt.Color(255, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 134, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 300));

        jPdatosVeh.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Tipo de vehículo:");

        jRcoche.setBackground(new java.awt.Color(255, 255, 255));
        bGtipoVeh.add(jRcoche);
        jRcoche.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRcoche.setForeground(new java.awt.Color(0, 0, 153));
        jRcoche.setText("Coche");

        jRmicro.setBackground(new java.awt.Color(255, 255, 255));
        bGtipoVeh.add(jRmicro);
        jRmicro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRmicro.setForeground(new java.awt.Color(0, 0, 153));
        jRmicro.setText("Microbus");

        jRcam.setBackground(new java.awt.Color(255, 255, 255));
        bGtipoVeh.add(jRcam);
        jRcam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRcam.setForeground(new java.awt.Color(0, 0, 153));
        jRcam.setText("Camión");

        jRfurgo.setBackground(new java.awt.Color(255, 255, 255));
        bGtipoVeh.add(jRfurgo);
        jRfurgo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jRfurgo.setForeground(new java.awt.Color(0, 0, 153));
        jRfurgo.setText("Furgoneta");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Marca:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Años:");

        jSanVeh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jSanVeh.setForeground(new java.awt.Color(0, 0, 153));
        jSanVeh.setMajorTickSpacing(1);
        jSanVeh.setMaximum(15);
        jSanVeh.setPaintLabels(true);
        jSanVeh.setValue(0);
        jSanVeh.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Color:");

        jCcolor.setBackground(new java.awt.Color(51, 134, 209));
        jCcolor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCcolor.setForeground(new java.awt.Color(0, 0, 153));
        jCcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Motor:");

        jCmotor.setBackground(new java.awt.Color(51, 134, 209));
        jCmotor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jCmotor.setForeground(new java.awt.Color(0, 0, 153));
        jCmotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----" }));

        jTFmarca.setBackground(new java.awt.Color(153, 204, 255));
        jTFmarca.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFmarca.setForeground(new java.awt.Color(0, 0, 153));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Cilindrada:");

        jTFcilin.setBackground(new java.awt.Color(153, 204, 255));
        jTFcilin.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFcilin.setForeground(new java.awt.Color(0, 0, 153));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Nº plazas:");

        jTFplazas.setBackground(new java.awt.Color(153, 204, 255));
        jTFplazas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFplazas.setForeground(new java.awt.Color(0, 0, 153));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("P.M.A.:");

        jTFpma.setBackground(new java.awt.Color(153, 204, 255));
        jTFpma.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFpma.setForeground(new java.awt.Color(0, 0, 153));

        jTFmetros.setBackground(new java.awt.Color(153, 204, 255));
        jTFmetros.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFmetros.setForeground(new java.awt.Color(0, 0, 153));

        jLmetros.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLmetros.setForeground(new java.awt.Color(0, 0, 153));
        jLmetros.setText("Metros:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nº ruedas:");

        jTFruedas.setBackground(new java.awt.Color(153, 204, 255));
        jTFruedas.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTFruedas.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jPdatosVehLayout = new javax.swing.GroupLayout(jPdatosVeh);
        jPdatosVeh.setLayout(jPdatosVehLayout);
        jPdatosVehLayout.setHorizontalGroup(
            jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosVehLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdatosVehLayout.createSequentialGroup()
                        .addComponent(jLmetros, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFmetros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFruedas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPdatosVehLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jRcoche)
                            .addGap(29, 29, 29)
                            .addComponent(jRmicro)
                            .addGap(28, 28, 28)
                            .addComponent(jRcam)
                            .addGap(34, 34, 34)
                            .addComponent(jRfurgo))
                        .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPdatosVehLayout.createSequentialGroup()
                                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPdatosVehLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSanVeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPdatosVehLayout.createSequentialGroup()
                                                .addComponent(jTFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPdatosVehLayout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jCcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFcilin))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPdatosVehLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFplazas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jTFpma, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPdatosVehLayout.setVerticalGroup(
            jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdatosVehLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRcoche)
                    .addComponent(jRmicro)
                    .addComponent(jRcam)
                    .addComponent(jRfurgo))
                .addGap(28, 28, 28)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSanVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcilin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFplazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFpma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFruedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPdatosVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLmetros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFmetros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        jPintroMat.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Matrícula:");

        jBanterior.setBackground(new java.awt.Color(51, 134, 209));
        jBanterior.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBanterior.setForeground(new java.awt.Color(255, 255, 255));
        jBanterior.setText("◄");
        jBanterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanteriorActionPerformed(evt);
            }
        });

        jBnext.setBackground(new java.awt.Color(51, 134, 209));
        jBnext.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBnext.setForeground(new java.awt.Color(255, 255, 255));
        jBnext.setText("►");
        jBnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnextActionPerformed(evt);
            }
        });

        jFTmat.setBackground(new java.awt.Color(255, 255, 255));
        jFTmat.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        jFTmat.setForeground(new java.awt.Color(0, 0, 153));
        try {
            jFTmat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####???")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTmat.setText("");
        jFTmat.setAlignmentX(10.0F);
        jFTmat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFTmat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jFTmat.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jFTmat.setPreferredSize(new java.awt.Dimension(38, 22));

        jBfirst.setBackground(new java.awt.Color(51, 134, 209));
        jBfirst.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBfirst.setForeground(new java.awt.Color(255, 255, 255));
        jBfirst.setText("l◄");
        jBfirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfirstActionPerformed(evt);
            }
        });

        jBlast.setBackground(new java.awt.Color(51, 134, 209));
        jBlast.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jBlast.setForeground(new java.awt.Color(255, 255, 255));
        jBlast.setText("►l");
        jBlast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPintroMatLayout = new javax.swing.GroupLayout(jPintroMat);
        jPintroMat.setLayout(jPintroMatLayout);
        jPintroMatLayout.setHorizontalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPintroMatLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jFTmat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jBfirst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBanterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBnext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBlast)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPintroMatLayout.setVerticalGroup(
            jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPintroMatLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBanterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBnext, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBfirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBlast, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPintroMatLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPintroMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTmat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar vehículos ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehículos:");

        jLtotalVeh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLtotalVeh.setForeground(new java.awt.Color(255, 255, 255));
        jLtotalVeh.setText("-");

        jBexit.setBackground(new java.awt.Color(255, 0, 0));
        jBexit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBexit.setForeground(new java.awt.Color(255, 255, 255));
        jBexit.setText("X");
        jBexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexitActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nº de vehículo:");

        jLvehAct.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLvehAct.setForeground(new java.awt.Color(255, 255, 255));
        jLvehAct.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPintroMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLtotalVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLvehAct, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPdatosVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBexit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLtotalVeh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLvehAct))))
                .addGap(17, 17, 17)
                .addComponent(jPintroMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPdatosVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jBexit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexitActionPerformed
        dispose();   
        try{
            con.cerrarConexion();
            
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBexitActionPerformed

    private void jBanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanteriorActionPerformed
       try{
            if (!con.isPrincipio()) {//si no es el primer elemento
                con.irAlAnterior();
                vehic = con.dameVehiAct();
                mostrarVehiculo(vehic);
                //actualizaBotones();
            }
        }
       catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBanteriorActionPerformed

    private void jBnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnextActionPerformed
        try{
            if (!con.isFinal()) {//si no es el último
                con.irAlSiguiente();
                vehic = con.dameVehiAct();
                mostrarVehiculo(vehic);
            }
        }
       catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jBnextActionPerformed

    private void jBfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfirstActionPerformed
        // primer vehiculo de la lista
         try{
            if (!con.isPrincipio()) {//si no es el último
                con.irAlPrimero();
                vehic = con.dameVehiAct();
                mostrarVehiculo(vehic);
            }
        }
       catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
      
    }//GEN-LAST:event_jBfirstActionPerformed

    private void jBlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlastActionPerformed
       try{
            if (!con.isFinal()) {//si no es el último
                con.irAlFinal();
                vehic = con.dameVehiAct();
                mostrarVehiculo(vehic);
            }
        }
       catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error de navegación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBlastActionPerformed
    
    
    public void mostrarVehiculo(Vehiculo veh){
        jFTmat.setText(veh.getMatrícula());
        jTFmarca.setText(veh.getMarca());
        jTFcilin.setText(Integer.toString(veh.getCilindrada()));
        jSanVeh.setValue(veh.getAnyos());
        jCcolor.setSelectedItem(veh.getColor().name());
        jCmotor.setSelectedItem(veh.getMotor().name());
        //atributos no comunes
        //limpiamos campos no comunes
        jTFruedas.setText("");
        jTFplazas.setText("");
        jTFpma.setText("");
        jTFmetros.setText("");
        if (veh instanceof Camion) {//vemos ejes
            jRcam.setSelected(true);
            jTFruedas.setText(Integer.toString(((Camion) veh).getRuedas()));
            jTFpma.setText(Integer.toString(((Camion)veh).getPma()));
        } else if (veh instanceof Coche) {
            jRcoche.setSelected(true);
            jTFplazas.setText(Integer.toString(((Coche) veh).getPlazas()));

        } else if (veh instanceof Furgo) {
            jRfurgo.setSelected(true);
            jTFplazas.setText(Integer.toString(((Furgo) veh).getPlazas()));
            jTFpma.setText(Integer.toString(((Furgo) veh).getPma()));
        } else {
            jRmicro.setSelected(true);
            jTFplazas.setText(Integer.toString(((MicroBus) veh).getPlazas()));
            jTFmetros.setText(Integer.toString(((MicroBus) veh).getMetros()));
        }

        //número de vehiculo en la lista
        try{
            jLvehAct.setText(Integer.toString(con.damePosAct()));
            actualizaBotones();
        }
       catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error al consultar nº vehículos!!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error al consultar nº vehículos!!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizaBotones() throws SQLException{
        //se deshabilitan todos
        jBanterior.setEnabled(false);
        jBnext.setEnabled(false);
        jBfirst.setEnabled(false);
        jBlast.setEnabled(false);
        
        //se habilitan según la posicion
        //si hay más de un vehículo
        if(con.tamanyo()>1){
            if(!con.isFinal()){//si no es el ultimo
                jBnext.setEnabled(true);
                jBlast.setEnabled(true);
            }
            if(!con.isPrincipio()){
                jBfirst.setEnabled(true);
                jBanterior.setEnabled(true);
            }
        }
    
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGtipoVeh;
    private javax.swing.JButton jBanterior;
    private javax.swing.JButton jBexit;
    private javax.swing.JButton jBfirst;
    private javax.swing.JButton jBlast;
    private javax.swing.JButton jBnext;
    private javax.swing.JComboBox<String> jCcolor;
    private javax.swing.JComboBox<String> jCmotor;
    private javax.swing.JFormattedTextField jFTmat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLmetros;
    private javax.swing.JLabel jLtotalVeh;
    private javax.swing.JLabel jLvehAct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPdatosVeh;
    private javax.swing.JPanel jPintroMat;
    private javax.swing.JRadioButton jRcam;
    private javax.swing.JRadioButton jRcoche;
    private javax.swing.JRadioButton jRfurgo;
    private javax.swing.JRadioButton jRmicro;
    private javax.swing.JSlider jSanVeh;
    private javax.swing.JTextField jTFcilin;
    private javax.swing.JTextField jTFmarca;
    private javax.swing.JTextField jTFmetros;
    private javax.swing.JTextField jTFplazas;
    private javax.swing.JTextField jTFpma;
    private javax.swing.JTextField jTFruedas;
    // End of variables declaration//GEN-END:variables
}
