/*
EJERCICIO Q15
 */
package frames;

import Ficheros.FicheroAlquiler;
import Ficheros.FicheroClientes;
import gestionBBDD.ConectaBBDD;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lidia Baixauli de la Villa
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private ConectaBBDD con = new ConectaBBDD();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);//para no redimensionar
        
        //deshabilitar ficheros. Ya se eliminarán los botones
        jMfix.setEnabled(false);
        jB_cargarFix_.setEnabled(false);
        jBguarda_datos_.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPvehic = new javax.swing.JPanel();
        jBveh_alta_ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBbajaVeh = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBmodVehic = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBverVehic = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPalq = new javax.swing.JPanel();
        jBalq_nuevo_ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBalq_devolver_ = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jBalq_modif_ = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jBAlq_cons_ = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPcond = new javax.swing.JPanel();
        jBcond_alta = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBcond_baja_ = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jBcond_mod = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jBconsulta_cond = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPotros = new javax.swing.JPanel();
        jBcalc_precio_ = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jBprecios_todos_ = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jBguarda_datos_ = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jB_cargarFix_ = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jMenuPpal = new javax.swing.JMenuBar();
        jMvehic_mod = new javax.swing.JMenu();
        jMenuItemAltaVeh = new javax.swing.JMenuItem();
        jMenuItemBajaVeh = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_vehCons = new javax.swing.JMenuItem();
        jMenuItem_vehConsTodos_ = new javax.swing.JMenuItem();
        jMenuItemVeh_mod = new javax.swing.JMenuItem();
        jMcond = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMcond_consDNI = new javax.swing.JMenuItem();
        jMcond_consTodos = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMalq = new javax.swing.JMenu();
        jMenuItem_alq_nuevp = new javax.swing.JMenuItem();
        jMenuItemAlq_baja_ = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_alqCons_mat = new javax.swing.JMenuItem();
        jMenuItem_alqCons_todos_ = new javax.swing.JMenuItem();
        jMenuItemVeh_mod1_ = new javax.swing.JMenuItem();
        jMprecios = new javax.swing.JMenu();
        jMenuItem_calPrecio_ = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMfix = new javax.swing.JMenu();
        jMenuItem1_cargaTodo_ = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMiCargarListaVeh = new javax.swing.JMenuItem();
        jMenuCarga_cond = new javax.swing.JMenuItem();
        jMenu_cargaAlq = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMiGuardaListaVeh = new javax.swing.JMenuItem();
        jM_Guardacond_ = new javax.swing.JMenuItem();
        jMenu_guardaAlq_ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal");
        setBackground(new java.awt.Color(0, 51, 255));
        setPreferredSize(new java.awt.Dimension(750, 760));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(51, 134, 209));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de alquiler");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPvehic.setBackground(new java.awt.Color(255, 255, 255));
        jPvehic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBveh_alta_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_alta.png"))); // NOI18N
        jBveh_alta_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBveh_alta_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBveh_alta_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBveh_alta_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBveh_alta_ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 134, 209));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vehículos");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Alta");

        jBbajaVeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_baja.png"))); // NOI18N
        jBbajaVeh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBbajaVeh.setMaximumSize(new java.awt.Dimension(55, 35));
        jBbajaVeh.setMinimumSize(new java.awt.Dimension(55, 35));
        jBbajaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaVehActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Baja");

        jBmodVehic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_mod2.png"))); // NOI18N
        jBmodVehic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBmodVehic.setMaximumSize(new java.awt.Dimension(55, 35));
        jBmodVehic.setMinimumSize(new java.awt.Dimension(55, 35));
        jBmodVehic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodVehicActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modificar");

        jBverVehic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche_cons.png"))); // NOI18N
        jBverVehic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBverVehic.setMaximumSize(new java.awt.Dimension(55, 35));
        jBverVehic.setMinimumSize(new java.awt.Dimension(55, 35));
        jBverVehic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBverVehicActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Consultar");

        javax.swing.GroupLayout jPvehicLayout = new javax.swing.GroupLayout(jPvehic);
        jPvehic.setLayout(jPvehicLayout);
        jPvehicLayout.setHorizontalGroup(
            jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPvehicLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBveh_alta_, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBverVehic, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBmodVehic, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBbajaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPvehicLayout.setVerticalGroup(
            jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPvehicLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPvehicLayout.createSequentialGroup()
                        .addComponent(jBveh_alta_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPvehicLayout.createSequentialGroup()
                        .addComponent(jBbajaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPvehicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPvehicLayout.createSequentialGroup()
                        .addComponent(jBmodVehic, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPvehicLayout.createSequentialGroup()
                        .addComponent(jBverVehic, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPalq.setBackground(new java.awt.Color(255, 255, 255));
        jPalq.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBalq_nuevo_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alq_alta.png"))); // NOI18N
        jBalq_nuevo_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBalq_nuevo_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBalq_nuevo_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBalq_nuevo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalq_nuevo_ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 134, 209));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alquiler");
        jLabel7.setToolTipText("");
        jLabel7.setOpaque(true);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Alquilar");

        jBalq_devolver_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alq_dev.png"))); // NOI18N
        jBalq_devolver_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBalq_devolver_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBalq_devolver_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBalq_devolver_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalq_devolver_ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Devolver");

        jBalq_modif_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alq_mod1.png"))); // NOI18N
        jBalq_modif_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBalq_modif_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBalq_modif_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBalq_modif_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalq_modif_ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Modificar");

        jBAlq_cons_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alq_cons.png"))); // NOI18N
        jBAlq_cons_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAlq_cons_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBAlq_cons_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBAlq_cons_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlq_cons_ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Consultar");

        javax.swing.GroupLayout jPalqLayout = new javax.swing.GroupLayout(jPalq);
        jPalq.setLayout(jPalqLayout);
        jPalqLayout.setHorizontalGroup(
            jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPalqLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBalq_nuevo_, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBAlq_cons_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBalq_modif_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBalq_devolver_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPalqLayout.setVerticalGroup(
            jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPalqLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPalqLayout.createSequentialGroup()
                        .addComponent(jBalq_nuevo_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPalqLayout.createSequentialGroup()
                        .addComponent(jBalq_devolver_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPalqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPalqLayout.createSequentialGroup()
                        .addComponent(jBalq_modif_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPalqLayout.createSequentialGroup()
                        .addComponent(jBAlq_cons_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPcond.setBackground(new java.awt.Color(255, 255, 255));
        jPcond.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBcond_alta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cond_alta.png"))); // NOI18N
        jBcond_alta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcond_alta.setMaximumSize(new java.awt.Dimension(55, 35));
        jBcond_alta.setMinimumSize(new java.awt.Dimension(55, 35));
        jBcond_alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcond_altaActionPerformed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 134, 209));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Conductores");
        jLabel17.setToolTipText("");
        jLabel17.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Alta");

        jBcond_baja_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cond_baja.png"))); // NOI18N
        jBcond_baja_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcond_baja_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBcond_baja_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBcond_baja_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcond_baja_ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Baja");

        jBcond_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cond_mod2.png"))); // NOI18N
        jBcond_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcond_mod.setMaximumSize(new java.awt.Dimension(55, 35));
        jBcond_mod.setMinimumSize(new java.awt.Dimension(55, 35));
        jBcond_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcond_modActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Modificar");

        jBconsulta_cond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cond_cons.png"))); // NOI18N
        jBconsulta_cond.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBconsulta_cond.setMaximumSize(new java.awt.Dimension(55, 35));
        jBconsulta_cond.setMinimumSize(new java.awt.Dimension(55, 35));
        jBconsulta_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsulta_condActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Consultar");

        javax.swing.GroupLayout jPcondLayout = new javax.swing.GroupLayout(jPcond);
        jPcond.setLayout(jPcondLayout);
        jPcondLayout.setHorizontalGroup(
            jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcondLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBcond_alta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBconsulta_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBcond_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBcond_baja_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPcondLayout.setVerticalGroup(
            jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcondLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcondLayout.createSequentialGroup()
                        .addComponent(jBcond_alta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPcondLayout.createSequentialGroup()
                        .addComponent(jBcond_baja_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPcondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPcondLayout.createSequentialGroup()
                        .addComponent(jBcond_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPcondLayout.createSequentialGroup()
                        .addComponent(jBconsulta_cond, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPotros.setBackground(new java.awt.Color(255, 255, 255));
        jPotros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBcalc_precio_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio_uno.png"))); // NOI18N
        jBcalc_precio_.setToolTipText("Ver precio por matrícula");
        jBcalc_precio_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBcalc_precio_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBcalc_precio_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBcalc_precio_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalc_precio_ActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(51, 134, 209));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Otros");
        jLabel22.setToolTipText("");
        jLabel22.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Calcular precio");

        jBprecios_todos_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio_todos.png"))); // NOI18N
        jBprecios_todos_.setToolTipText("Precio de todos los vehículos");
        jBprecios_todos_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBprecios_todos_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBprecios_todos_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBprecios_todos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBprecios_todos_ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Ver precios");

        jBguarda_datos_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche1.png"))); // NOI18N
        jBguarda_datos_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBguarda_datos_.setMaximumSize(new java.awt.Dimension(55, 35));
        jBguarda_datos_.setMinimumSize(new java.awt.Dimension(55, 35));
        jBguarda_datos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguarda_datos_ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Guardar datos");

        jB_cargarFix_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche1.png"))); // NOI18N
        jB_cargarFix_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jB_cargarFix_.setMaximumSize(new java.awt.Dimension(55, 35));
        jB_cargarFix_.setMinimumSize(new java.awt.Dimension(55, 35));
        jB_cargarFix_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cargarFix_ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Cargar datos");

        javax.swing.GroupLayout jPotrosLayout = new javax.swing.GroupLayout(jPotros);
        jPotros.setLayout(jPotrosLayout);
        jPotrosLayout.setHorizontalGroup(
            jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPotrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBcalc_precio_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jB_cargarFix_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBguarda_datos_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBprecios_todos_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPotrosLayout.setVerticalGroup(
            jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPotrosLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPotrosLayout.createSequentialGroup()
                        .addComponent(jBcalc_precio_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(jPotrosLayout.createSequentialGroup()
                        .addComponent(jBprecios_todos_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPotrosLayout.createSequentialGroup()
                        .addComponent(jBguarda_datos_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(jPotrosLayout.createSequentialGroup()
                        .addComponent(jB_cargarFix_, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPalq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPvehic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPcond, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPotros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPvehic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPcond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPalq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPotros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jMenuPpal.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 1, 10, new java.awt.Color(51, 134, 209)));
        jMenuPpal.setToolTipText("");
        jMenuPpal.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jMenuPpal.setOpaque(true
        );
        jMenuPpal.setPreferredSize(new java.awt.Dimension(350, 40));

        jMvehic_mod.setBackground(new java.awt.Color(51, 134, 209));
        jMvehic_mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 134, 209)));
        jMvehic_mod.setForeground(new java.awt.Color(0, 0, 153));
        jMvehic_mod.setMnemonic('V');
        jMvehic_mod.setText("        Vehículos");
        jMvehic_mod.setToolTipText("");
        jMvehic_mod.setBorderPainted(true);
        jMvehic_mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMvehic_mod.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMvehic_mod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMvehic_mod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMvehic_mod.setPreferredSize(new java.awt.Dimension(150, 50));
        jMvehic_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMvehic_modActionPerformed(evt);
            }
        });

        jMenuItemAltaVeh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAltaVeh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemAltaVeh.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemAltaVeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_che.png"))); // NOI18N
        jMenuItemAltaVeh.setText("Alta vehículo");
        jMenuItemAltaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaVehActionPerformed(evt);
            }
        });
        jMvehic_mod.add(jMenuItemAltaVeh);

        jMenuItemBajaVeh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemBajaVeh.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemBajaVeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_delete.png"))); // NOI18N
        jMenuItemBajaVeh.setText("Baja vehículo");
        jMenuItemBajaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaVehActionPerformed(evt);
            }
        });
        jMvehic_mod.add(jMenuItemBajaVeh);

        jMenu3.setForeground(new java.awt.Color(0, 0, 153));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meni_cons.png"))); // NOI18N
        jMenu3.setText("Consultar...");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem_vehCons.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_vehCons.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_vehCons.setText("por matrícula");
        jMenuItem_vehCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_vehConsActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_vehCons);

        jMenuItem_vehConsTodos_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_vehConsTodos_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_vehConsTodos_.setText("todos");
        jMenuItem_vehConsTodos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_vehConsTodos_ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_vehConsTodos_);

        jMvehic_mod.add(jMenu3);

        jMenuItemVeh_mod.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemVeh_mod.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemVeh_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod_menu.png"))); // NOI18N
        jMenuItemVeh_mod.setText("Modificar");
        jMenuItemVeh_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeh_modActionPerformed(evt);
            }
        });
        jMvehic_mod.add(jMenuItemVeh_mod);

        jMenuPpal.add(jMvehic_mod);

        jMcond.setBackground(new java.awt.Color(51, 134, 209));
        jMcond.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 134, 209)));
        jMcond.setForeground(new java.awt.Color(0, 0, 153));
        jMcond.setMnemonic('C');
        jMcond.setText("    Conductores");
        jMcond.setToolTipText("");
        jMcond.setBorderPainted(true);
        jMcond.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMcond.setFocusPainted(true);
        jMcond.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMcond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMcond.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMcond.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_che.png"))); // NOI18N
        jMenuItem3.setText("Alta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMcond.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_delete.png"))); // NOI18N
        jMenuItem4.setText("Baja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMcond.add(jMenuItem4);

        jMenu4.setForeground(new java.awt.Color(0, 0, 153));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meni_cons.png"))); // NOI18N
        jMenu4.setText("Consultar");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMcond_consDNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMcond_consDNI.setForeground(new java.awt.Color(0, 0, 153));
        jMcond_consDNI.setText("por DNI");
        jMcond_consDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcond_consDNIActionPerformed(evt);
            }
        });
        jMenu4.add(jMcond_consDNI);

        jMcond_consTodos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMcond_consTodos.setForeground(new java.awt.Color(0, 0, 153));
        jMcond_consTodos.setText("todos");
        jMcond_consTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcond_consTodosActionPerformed(evt);
            }
        });
        jMenu4.add(jMcond_consTodos);

        jMcond.add(jMenu4);

        jMenuItem5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod_menu.png"))); // NOI18N
        jMenuItem5.setText("Modificar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMcond.add(jMenuItem5);

        jMenuPpal.add(jMcond);

        jMalq.setBackground(new java.awt.Color(51, 134, 209));
        jMalq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 134, 209)));
        jMalq.setForeground(new java.awt.Color(0, 0, 153));
        jMalq.setMnemonic('A');
        jMalq.setText("          Alquiler");
        jMalq.setBorderPainted(true);
        jMalq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMalq.setFocusPainted(true);
        jMalq.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMalq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMalq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMalq.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_alq_nuevp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_alq_nuevp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_alq_nuevp.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_alq_nuevp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_che.png"))); // NOI18N
        jMenuItem_alq_nuevp.setText("Nuevo Alquiler");
        jMenuItem_alq_nuevp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_alq_nuevpActionPerformed(evt);
            }
        });
        jMalq.add(jMenuItem_alq_nuevp);

        jMenuItemAlq_baja_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemAlq_baja_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemAlq_baja_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_delete.png"))); // NOI18N
        jMenuItemAlq_baja_.setText("Devolver vehículo");
        jMenuItemAlq_baja_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlq_baja_ActionPerformed(evt);
            }
        });
        jMalq.add(jMenuItemAlq_baja_);

        jMenu5.setForeground(new java.awt.Color(0, 0, 153));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/meni_cons.png"))); // NOI18N
        jMenu5.setText("Consultar...");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem_alqCons_mat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_alqCons_mat.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_alqCons_mat.setText("por matrícula");
        jMenuItem_alqCons_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_alqCons_matActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_alqCons_mat);

        jMenuItem_alqCons_todos_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_alqCons_todos_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_alqCons_todos_.setText("todos");
        jMenuItem_alqCons_todos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_alqCons_todos_ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_alqCons_todos_);

        jMalq.add(jMenu5);

        jMenuItemVeh_mod1_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItemVeh_mod1_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemVeh_mod1_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mod_menu.png"))); // NOI18N
        jMenuItemVeh_mod1_.setText("Modificar");
        jMenuItemVeh_mod1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeh_mod1_ActionPerformed(evt);
            }
        });
        jMalq.add(jMenuItemVeh_mod1_);

        jMenuPpal.add(jMalq);

        jMprecios.setBackground(new java.awt.Color(51, 134, 209));
        jMprecios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 134, 209)));
        jMprecios.setForeground(new java.awt.Color(0, 0, 153));
        jMprecios.setMnemonic('P');
        jMprecios.setText("          Precios");
        jMprecios.setToolTipText("");
        jMprecios.setBorderPainted(true);
        jMprecios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMprecios.setFocusPainted(true);
        jMprecios.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMprecios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMprecios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMprecios.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_calPrecio_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem_calPrecio_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem_calPrecio_.setText("Calcular");
        jMenuItem_calPrecio_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_calPrecio_ActionPerformed(evt);
            }
        });
        jMprecios.add(jMenuItem_calPrecio_);

        jMenuItem9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem9.setText("Ver precios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMprecios.add(jMenuItem9);

        jMenuPpal.add(jMprecios);

        jMfix.setBackground(new java.awt.Color(51, 134, 209));
        jMfix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 134, 209)));
        jMfix.setForeground(new java.awt.Color(0, 0, 153));
        jMfix.setMnemonic('F');
        jMfix.setText("        Ficheros");
        jMfix.setToolTipText("");
        jMfix.setBorderPainted(true);
        jMfix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMfix.setFocusPainted(true);
        jMfix.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMfix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMfix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMfix.setPreferredSize(new java.awt.Dimension(153, 50));
        jMfix.setRequestFocusEnabled(false);

        jMenuItem1_cargaTodo_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem1_cargaTodo_.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem1_cargaTodo_.setText("Cargar todo");
        jMenuItem1_cargaTodo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_cargaTodo_ActionPerformed(evt);
            }
        });
        jMfix.add(jMenuItem1_cargaTodo_);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 153));
        jMfix.add(jSeparator1);

        jMenuItem10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem10.setText("Guardar todo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMfix.add(jMenuItem10);

        jMenu1.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("Cargar...");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMiCargarListaVeh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMiCargarListaVeh.setForeground(new java.awt.Color(0, 0, 153));
        jMiCargarListaVeh.setText("Vehículos");
        jMiCargarListaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiCargarListaVehActionPerformed(evt);
            }
        });
        jMenu1.add(jMiCargarListaVeh);

        jMenuCarga_cond.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuCarga_cond.setForeground(new java.awt.Color(0, 0, 153));
        jMenuCarga_cond.setText("Conductores");
        jMenuCarga_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarga_condActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCarga_cond);

        jMenu_cargaAlq.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenu_cargaAlq.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_cargaAlq.setText("Alquileres");
        jMenu_cargaAlq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_cargaAlqActionPerformed(evt);
            }
        });
        jMenu1.add(jMenu_cargaAlq);

        jMfix.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 153));
        jMenu2.setText("Guardar...");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMiGuardaListaVeh.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMiGuardaListaVeh.setForeground(new java.awt.Color(0, 0, 153));
        jMiGuardaListaVeh.setText("Vehículos");
        jMiGuardaListaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiGuardaListaVehActionPerformed(evt);
            }
        });
        jMenu2.add(jMiGuardaListaVeh);

        jM_Guardacond_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jM_Guardacond_.setForeground(new java.awt.Color(0, 0, 153));
        jM_Guardacond_.setText("Conductores");
        jM_Guardacond_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_Guardacond_ActionPerformed(evt);
            }
        });
        jMenu2.add(jM_Guardacond_);

        jMenu_guardaAlq_.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenu_guardaAlq_.setForeground(new java.awt.Color(0, 0, 153));
        jMenu_guardaAlq_.setText("Alquileres");
        jMenu_guardaAlq_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_guardaAlq_ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu_guardaAlq_);

        jMfix.add(jMenu2);

        jMenuPpal.add(jMfix);

        setJMenuBar(jMenuPpal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBveh_alta_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBveh_alta_ActionPerformed
        // abre jF nuevo vehículo. Mandamos la listaveh
        JFveh_alta altaVeh = new JFveh_alta();
        altaVeh.setVisible(true);
    }//GEN-LAST:event_jBveh_alta_ActionPerformed

    private void jBverVehicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBverVehicActionPerformed
        //consultar vehiculos
        //todos y por matricula
        String[] valores = {"Consulta un vehículo", "Ver todos"};
        int tamanyo=-1;
        tamanyo = verTamanyo("Vehiculos");

        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {
            int op = JOptionPane.showOptionDialog(this, "Selecicione una opción", "Consulta vehículos", WIDTH, JOptionPane.QUESTION_MESSAGE, null, valores, valores[0]);
            if (op == 0) {
                //consulta veh por matricula
                JFveh_consulta consVeh = new JFveh_consulta();
                consVeh.setVisible(true);
            } else {
                JFveh_consTodos todVeh = new JFveh_consTodos();
                todVeh.setVisible(true);
            }
        }
    }//GEN-LAST:event_jBverVehicActionPerformed

    private void jBbajaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaVehActionPerformed
       //elimina vehiculo
       int tamanyo=-1;
       tamanyo = verTamanyo("Vehiculos");
        
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {
            JFveh_baja ventBorra = new JFveh_baja();
            ventBorra.setVisible(true);
        }
    }//GEN-LAST:event_jBbajaVehActionPerformed

    private void jBmodVehicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodVehicActionPerformed
        //modificar vehiculos 
        int tamanyo=-1;
       tamanyo = verTamanyo("Vehiculos");
        
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {
            JFveh_modificar ventMod = new JFveh_modificar();
            ventMod.setVisible(true);
        }
    }//GEN-LAST:event_jBmodVehicActionPerformed

    private void jMiCargarListaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiCargarListaVehActionPerformed
       //cargar el fichero de vehiculos
//       try{
//           boolean cargado = Ficheros.cargarVehiculos(listaVeh);
//           if(cargado){
//               JOptionPane.showMessageDialog(this, "Lista de vehículos cargada con éxito");
//           }
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//       }
    }//GEN-LAST:event_jMiCargarListaVehActionPerformed

    private void jMiGuardaListaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiGuardaListaVehActionPerformed
//        //guardar vehículos
//         try{
//           boolean guardado = Ficheros.guardarVehiculos(listaVeh);
//           if(guardado){
//               JOptionPane.showMessageDialog(this, "Lista de vehículos guardada");
//           }
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);
//       }
    }//GEN-LAST:event_jMiGuardaListaVehActionPerformed

    private void jMenuItemAltaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaVehActionPerformed
        jBveh_alta_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemAltaVehActionPerformed

    private void jBcond_altaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcond_altaActionPerformed
        //nuevo conductor
        JFcond_alta ventAltaCond= new JFcond_alta();
        ventAltaCond.setVisible(true);
    }//GEN-LAST:event_jBcond_altaActionPerformed

    private void jBcond_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcond_modActionPerformed
        //modif conductor
        int tamanyo = -1;
        tamanyo = verTamanyo("Clientes");
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay conductores en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {
            JFcond_mod ventCon = new JFcond_mod();
            ventCon.setVisible(true);
        }
    }//GEN-LAST:event_jBcond_modActionPerformed

    private void jM_Guardacond_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_Guardacond_ActionPerformed
       //guardar conductores
//         try{
//           boolean guardado = FicheroClientes.guardarConductor(listaCond);
//           if(guardado){
//               JOptionPane.showMessageDialog(this, "Lista de conductores guardada");
//           }
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);
//       }
    }//GEN-LAST:event_jM_Guardacond_ActionPerformed

    private void jMenuCarga_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarga_condActionPerformed
         //cargar el fichero de cond
//       try{
//           boolean cargado = FicheroClientes.cargarConductor(listaCond);
//           if(cargado){
//               JOptionPane.showMessageDialog(this, "Lista de conductores cargada");
//           }
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//       }
    }//GEN-LAST:event_jMenuCarga_condActionPerformed

    private void jBconsulta_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsulta_condActionPerformed
        //consultaer conductores
        //ver todos y por DNI
        int tamanyo=-1;
        tamanyo = verTamanyo("Clientes");
        String[] valores = {"Consulta un conductor", "Ver todos"};
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay conductores en el sistema","Lista vacía",JOptionPane.ERROR_MESSAGE);
        } else {
            int op = JOptionPane.showOptionDialog(this, "Selecicione una opción", "Consulta Conductores", WIDTH, JOptionPane.QUESTION_MESSAGE, null, valores, valores[0]);
            if (op == 0) {
                //consulta veh por dni
                JFcond_consultaDni consC = new JFcond_consultaDni();
                consC.setVisible(true);
            } else {
                JFcond_consultaTodos todVeh = new JFcond_consultaTodos();
                todVeh.setVisible(true);
            }
        }
    }//GEN-LAST:event_jBconsulta_condActionPerformed

    private void jBcond_baja_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcond_baja_ActionPerformed
        //eliminar conductor
        //Si tiene alquileres no se puede eliminar
        int tamanyo=-1;
        tamanyo = verTamanyo("Clientes");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay conductores en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } 
       else{//cargar frame
            JFcond_baja con_baja = new JFcond_baja();
            con_baja.setVisible(true);
        }
    }//GEN-LAST:event_jBcond_baja_ActionPerformed

    private void jBalq_nuevo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalq_nuevo_ActionPerformed
        //nuevo alquiler
        
        boolean hayVeh=false, hayClientes=true;
        try{
            con.conecta();
            con.crearSentencia();
            con.cargaTabla("Vehiculos");
            if(con.tamanyo()>0){
                hayVeh = true;
            }
            con.cargaTabla("Clientes");
            if(con.tamanyo()>0){
                hayClientes = true;
            }
            con.cerrarConexion();
        }
          catch (SQLException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error clientes!!", JOptionPane.ERROR_MESSAGE);
        }
       
        //se mandan las tres listas
        if(!hayClientes){
                    JOptionPane.showMessageDialog(null, "No hay conductores en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);

        }
        if(!hayVeh){
                    JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);

        }
        if (hayClientes && hayVeh) {
            JFalq_nuevo alq = new JFalq_nuevo();
            alq.setVisible(true);
        }
    }//GEN-LAST:event_jBalq_nuevo_ActionPerformed

    private void jBcalc_precio_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalc_precio_ActionPerformed
        //para ver precio de un vehic. 
        //se manda lista alquiler para saber si el vehic está disponible o no
        int tamanyo=-1;
        tamanyo = verTamanyo("Vehiculos");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {

            JFprecio_vehiculo vent = new JFprecio_vehiculo();
            vent.setVisible(true);
        }
    }//GEN-LAST:event_jBcalc_precio_ActionPerformed

    private void jBprecios_todos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBprecios_todos_ActionPerformed
        //para ver precio de todos los  vehic. 
        //se manda lista alquiler para saber si el vehic está disponible o no
        int tamanyo=-1;
        tamanyo = verTamanyo("Vehiculos");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        } else {

            JFprecio_todos vent = new JFprecio_todos();
            vent.setVisible(true);
        }
    }//GEN-LAST:event_jBprecios_todos_ActionPerformed

    private void jMenuItemBajaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaVehActionPerformed
        jBbajaVehActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemBajaVehActionPerformed

    private void jMvehic_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMvehic_modActionPerformed
       jBmodVehicActionPerformed(evt);
     
    }//GEN-LAST:event_jMvehic_modActionPerformed

    private void jMenuItemVeh_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeh_modActionPerformed
        jBmodVehicActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemVeh_modActionPerformed

    private void jMenuItem_vehConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_vehConsActionPerformed
        int tamanyo=-1;
        tamanyo = verTamanyo("Vehiculos");
        if (tamanyo == 0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        }  else {
            JFveh_consulta consVeh = new JFveh_consulta();
            consVeh.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem_vehConsActionPerformed

    private void jMenuItem_vehConsTodos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_vehConsTodos_ActionPerformed
        // consulta todos los vehi
        int tamanyo=-1;
        tamanyo = verTamanyo("Vehiculos");
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay vehículos en el sistema", "Lista vacía", JOptionPane.ERROR_MESSAGE);
        }  else {
            JFveh_consTodos todVeh = new JFveh_consTodos();
            todVeh.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem_vehConsTodos_ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jBcond_altaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jBcond_baja_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMcond_consDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcond_consDNIActionPerformed
        //consulta conductor por dni
        int tamanyo=-1;
        tamanyo = verTamanyo("Clientes");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay conductores en el sistema","Lista vacía",JOptionPane.ERROR_MESSAGE);
        } else {JFcond_consultaDni consC = new JFcond_consultaDni();
                consC.setVisible(true);
        }
    }//GEN-LAST:event_jMcond_consDNIActionPerformed

    private void jMcond_consTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcond_consTodosActionPerformed
        //consulta todos llos conductores
        int tamanyo=-1;
        tamanyo = verTamanyo("Clientes");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay conductores en el sistema","Lista vacía",JOptionPane.ERROR_MESSAGE);
        } else {
        JFcond_consultaTodos todVeh = new JFcond_consultaTodos();
                todVeh.setVisible(true);
        }
    }//GEN-LAST:event_jMcond_consTodosActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jBcond_modActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem_alq_nuevpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_alq_nuevpActionPerformed
        jBalq_nuevo_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_alq_nuevpActionPerformed

    private void jMenuItemAlq_baja_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlq_baja_ActionPerformed
        jBalq_devolver_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemAlq_baja_ActionPerformed

    private void jMenuItem_alqCons_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_alqCons_matActionPerformed
        int tamanyo=-1;
        tamanyo = verTamanyo("Alquiler");
        if (tamanyo<=0){
            JOptionPane.showMessageDialog(null, "No hay alquileres activos","Nada alquilado",JOptionPane.ERROR_MESSAGE);
        }else{
            JFalq_consulta ventAlq = new JFalq_consulta();
                ventAlq.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem_alqCons_matActionPerformed

    private void jMenuItem_alqCons_todos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_alqCons_todos_ActionPerformed
        int tamanyo=-1;
        tamanyo = verTamanyo("Alquiler");
        if (tamanyo<=0){
            JOptionPane.showMessageDialog(null, "No hay alquileres activos","Nada alquilado",JOptionPane.ERROR_MESSAGE);
        }else{
            JFalq_consultaTodos ventAlq = new JFalq_consultaTodos();
                ventAlq.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem_alqCons_todos_ActionPerformed

    private void jMenuItemVeh_mod1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeh_mod1_ActionPerformed
        jBalq_modif_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemVeh_mod1_ActionPerformed

    private void jMenu_cargaAlqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_cargaAlqActionPerformed
          //cargar el fichero de alq
//        try {
//            boolean cargado = FicheroAlquiler.cargarAlquiler();
//            if (cargado) {
//                JOptionPane.showMessageDialog(this, "Lista de alquileres cargada");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jMenu_cargaAlqActionPerformed

    private void jMenu_guardaAlq_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_guardaAlq_ActionPerformed
        //guardar alq
        try {
            //boolean guardado = FicheroAlquiler.guardarAlquiler();
//            if (guardado) {
//                JOptionPane.showMessageDialog(this, "Lista de alquileres guardada");
//            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);


        }    }//GEN-LAST:event_jMenu_guardaAlq_ActionPerformed

    private void jBAlq_cons_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlq_cons_ActionPerformed
        //consultar alquileres 
        String[] valores = {"Consultar alquileres", "Ver todos"};
        int tamanyo=-1;
        tamanyo = verTamanyo("Alquiler");
        if (tamanyo<=0) {
            JOptionPane.showMessageDialog(null, "No hay alquileres en el sistema","Lista vacía",JOptionPane.ERROR_MESSAGE);
        } else {
            int op = JOptionPane.showOptionDialog(this, "Selecicione una opción", "Consulta Alquileres", WIDTH, JOptionPane.QUESTION_MESSAGE, null, valores, valores[0]);
            if (op == 0) {
                //consulta introduciendo datos
                JFalq_consulta ventAlq = new JFalq_consulta();
                ventAlq.setVisible(true);
            } else {
                JFalq_consultaTodos todAlq = new JFalq_consultaTodos();
                todAlq.setVisible(true);
            }
        }
    }//GEN-LAST:event_jBAlq_cons_ActionPerformed

    private void jMenuItem1_cargaTodo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_cargaTodo_ActionPerformed
//        boolean cargado = false,cargadoC = false,cargadoAlq = false;
//                //cargar el fichero de vehiculos
//        try {
//            cargado = Ficheros.cargarVehiculos();
//            if (!cargado) {
//                JOptionPane.showMessageDialog(null, "Lista de vehículos vacía", "Sin vehículos", JOptionPane.ERROR_MESSAGE);
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista de vehículos", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//        }
//
//        //cargar el fichero de cond
//        try {
//           cargadoC = FicheroClientes.cargarConductor();
//if (!cargadoC) {
//                JOptionPane.showMessageDialog(null, "Lista de conductores vacía", "Sin conductores", JOptionPane.ERROR_MESSAGE);
//            }
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//       }
//       
//         //cargar el fichero de alq
//        try {
//            cargadoAlq = FicheroAlquiler.cargarAlquiler(listaAlq);
//            if (!cargadoAlq) {
//                JOptionPane.showMessageDialog(null, "Lista de alquileres vacía", "Sin alquileres", JOptionPane.ERROR_MESSAGE);
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "No se ha podido cargar la lista de alquileres", "Error al cargar", JOptionPane.ERROR_MESSAGE);
//        }
//       
//        if(cargado && cargadoC && cargadoAlq){
//            JOptionPane.showMessageDialog(this, "Listas cargadas con éxito");
//        }
       
       
    }//GEN-LAST:event_jMenuItem1_cargaTodo_ActionPerformed

    private void jB_cargarFix_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cargarFix_ActionPerformed
        jMenuItem1_cargaTodo_ActionPerformed(evt);
    }//GEN-LAST:event_jB_cargarFix_ActionPerformed

    private void jBalq_modif_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalq_modif_ActionPerformed
        //modif alquileres
         int tamanyo=-1;
       tamanyo = verTamanyo("Alquiler");
        if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay alquileres activos","Nada alquilado",JOptionPane.ERROR_MESSAGE);
        } else {
            JFalq_modificar ventAl = new JFalq_modificar();
            ventAl.setVisible(true);
        }
    }//GEN-LAST:event_jBalq_modif_ActionPerformed

    private void jBalq_devolver_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalq_devolver_ActionPerformed
        //devolver alq
         int tamanyo;
         tamanyo = verTamanyo("Alquiler");
         if (tamanyo <= 0) {
            JOptionPane.showMessageDialog(null, "No hay alquileres activos","Nada alquilado",JOptionPane.ERROR_MESSAGE);
        } else {
            JFalq_devolver ventAl = new JFalq_devolver();
            ventAl.setVisible(true);
        }
    }//GEN-LAST:event_jBalq_devolver_ActionPerformed

    private void jBguarda_datos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguarda_datos_ActionPerformed
        // guarda tosdos los ficheros
//        boolean guardadoV = false,guardadoA = false,guardadoC =false;
//        //vehiculos
//        try{
//           guardadoV = Ficheros.guardarVehiculos(listaVeh);
//           
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);
//       }
//        
//        //guardar conductores
//         try{
//           guardadoC = FicheroClientes.guardarConductor(listaCond);
//           
//       }
//       catch(Exception e){
//           JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);
//       }
//         
//         //guardar alq
//        try {
//            guardadoA = FicheroAlquiler.guardarAlquiler(listaAlq);
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Lista No guardada", "Error al guardar", JOptionPane.ERROR_MESSAGE);
//            
//        } 
//        
//        if(guardadoC && guardadoA && guardadoV){
//               JOptionPane.showMessageDialog(this, "Listas guardadas");
//           }
//         
    }//GEN-LAST:event_jBguarda_datos_ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jBguarda_datos_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem_calPrecio_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_calPrecio_ActionPerformed
        jBcalc_precio_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_calPrecio_ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jBprecios_todos_ActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    //ver los tamaños de las tablas
    public int verTamanyo(String nomTabla){
        int tamanyo=0;
        try {
            con.conecta();
            con.crearSentencia();
            con.cargaTabla(nomTabla);
            tamanyo = con.tamanyo();
            con.cerrarConexion();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error SQL. En " + nomTabla, JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error!!", JOptionPane.ERROR_MESSAGE);
        }
        return tamanyo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlq_cons_;
    private javax.swing.JButton jB_cargarFix_;
    private javax.swing.JButton jBalq_devolver_;
    private javax.swing.JButton jBalq_modif_;
    private javax.swing.JButton jBalq_nuevo_;
    private javax.swing.JButton jBbajaVeh;
    private javax.swing.JButton jBcalc_precio_;
    private javax.swing.JButton jBcond_alta;
    private javax.swing.JButton jBcond_baja_;
    private javax.swing.JButton jBcond_mod;
    private javax.swing.JButton jBconsulta_cond;
    private javax.swing.JButton jBguarda_datos_;
    private javax.swing.JButton jBmodVehic;
    private javax.swing.JButton jBprecios_todos_;
    private javax.swing.JButton jBveh_alta_;
    private javax.swing.JButton jBverVehic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jM_Guardacond_;
    private javax.swing.JMenu jMalq;
    private javax.swing.JMenu jMcond;
    private javax.swing.JMenuItem jMcond_consDNI;
    private javax.swing.JMenuItem jMcond_consTodos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuCarga_cond;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem1_cargaTodo_;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAlq_baja_;
    private javax.swing.JMenuItem jMenuItemAltaVeh;
    private javax.swing.JMenuItem jMenuItemBajaVeh;
    private javax.swing.JMenuItem jMenuItemVeh_mod;
    private javax.swing.JMenuItem jMenuItemVeh_mod1_;
    private javax.swing.JMenuItem jMenuItem_alqCons_mat;
    private javax.swing.JMenuItem jMenuItem_alqCons_todos_;
    private javax.swing.JMenuItem jMenuItem_alq_nuevp;
    private javax.swing.JMenuItem jMenuItem_calPrecio_;
    private javax.swing.JMenuItem jMenuItem_vehCons;
    private javax.swing.JMenuItem jMenuItem_vehConsTodos_;
    private javax.swing.JMenuBar jMenuPpal;
    private javax.swing.JMenuItem jMenu_cargaAlq;
    private javax.swing.JMenuItem jMenu_guardaAlq_;
    private javax.swing.JMenu jMfix;
    private javax.swing.JMenuItem jMiCargarListaVeh;
    private javax.swing.JMenuItem jMiGuardaListaVeh;
    private javax.swing.JMenu jMprecios;
    private javax.swing.JMenu jMvehic_mod;
    private javax.swing.JPanel jPalq;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPcond;
    private javax.swing.JPanel jPotros;
    private javax.swing.JPanel jPvehic;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
